### PR TITLE
no not ignore OpenSSL errors in CSR generation

### LINKED ISSUE #119: engine_openssl.c:generate_csr always returns 0 regardless of success/failure
@qrkourier filed a ziti edge tunnel issue over at https://github.com/openziti/ziti-tunnel-sdk-c/issues/517 After investigation, we see the `generate_csr` function only returns 0, regardless of what happens in the function's openssl calls. There are numerous opportunities in that `generate_csr` for return openssl values to be checked which are not currently being checked. 

It seems to have something to do with RedHat 9 since it is only observed when running a tunneler in RedHat 9 (not RedHat 8 or other environments). 

Since this function always returns 0, when something openssl + RedHat 9 related goes wrong, the CSR is an empty string/uninitialize and thus the tunneler ends up sending an CSR to the controller.

Update the engine_openssl.c to return/log errors

### PR DESCRIPTION
**Pull request by ekoby**
[fixes #119]

### CODE REVIEW

File: src/engine_openssl.c [hunk 1]
```diff
@@ -891,21 +894,30 @@ static int generate_csr(tls_private_key key, char **pem, size_t *pemlen, ...) {
         X509_NAME_add_entry_by_txt(subj, id, MBSTRING_ASC, val, -1, -1, 0);
     }
 
+#define ssl_check(OP) do{ \
+op = #OP;                          \
+if((OP) == 0) {             \
+ret = ERR_get_error();\
+goto on_error;\
```
Comment (dovholuknf) [inline src/engine_openssl.c:901]: i appreciate that not a single line has the continuation character at the same location.

File: src/engine_openssl.c [hunk 2]
```diff
@@ -891,21 +894,30 @@ static int generate_csr(tls_private_key key, char **pem, size_t *pemlen, ...) {
...
+    ssl_check(X509_REQ_set_pubkey(req, pk));
+    ssl_check(X509_REQ_sign(req, pk, EVP_sha1()));
+    ssl_check(PEM_write_bio_X509_REQ(b, req));
 
-    size_t len = BIO_ctrl_pending(b);
-    *pem = calloc(1, len + 1);
-    BIO_read(b, *pem, len);
+    on_error:
+    if (ret) {
+        UM_LOG(WARN, "%s => %s", op, tls_error(ret));
```
Comment (dovholuknf) [inline src/engine_openssl.c:910]: why only WARN? Why not ERROR?

Comment (ekoby) [reply src/engine_openssl.c:910]: Application can handle error as it sees fit

File: src/engine_openssl.c [hunk 3]
```diff
@@ -891,21 +894,30 @@ static int generate_csr(tls_private_key key, char **pem, size_t *pemlen, ...) {
         X509_NAME_add_entry_by_txt(subj, id, MBSTRING_ASC, val, -1, -1, 0);
     }
 
+#define ssl_check(OP) do{ \
+op = #OP;                          \
+if((OP) == 0) {             \
```
Comment (dovholuknf) [inline src/engine_openssl.c:899]: should this be < 1 just in case one of these functions ever decides to return a negative value to indicate failure? i checked the three that were used already but it seems like it might be a good idea?

**Review by dovholuknf — APPROVED** [review]

File: src/engine_openssl.c (hunk 3 above)
Comment (ekoby) [reply src/engine_openssl.c]: 0 for error is the standard for all OpenSSL functions
